version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
